name: Practice Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Directory
        run: pwd

      - name: Show Files
        run: ls -la

      - name: Print Message
        run: echo "Build Started"

      - name: Run App
        run: node app.js

      - name: Build Finished
        run: echo "Build Completed"